version: "3.8"

services:
#  db:
#    image: mysql:8.0.26
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#  db:
#    build: ./backend_db
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=root

  backend:
#    depends_on:
#      - db
    build: .
    ports:
      - "5000:5000"
      - "5555:5555"
    environment:
      JWT_SECRET: fruit
#      DATABASE_URL: mysql://root:root@db:3306/libraryly
#    command: ./starting-script.sh