module.exports = [
    {
        title: "Alice’s Adventures in Wonderland",
        stock: 7,
        isbn: "9780194227230",
        imageUrl: "https://image.example.com",
        pages: 192,
        authorId: 1,
        genreId: 1,
    },
    {
        title: "The King of Elfland\'s Daughter",
        stock: 5,
        isbn: "9780345216281",
        imageUrl: "https://image.example.com",
        pages: 301,
        authorId: 2,
        genreId: 1,
    },
    {
        title: "The Sword in the Stone",
        stock: 2,
        isbn: "9780006753995",
        imageUrl: "https://image.example.com",
        pages: 312,
        authorId: 3,
        genreId: 1,
    },
    {
        title: "The Lion, the Witch, and the Wardrobe",
        stock: 9,
        isbn: "9780060276362",
        imageUrl: "https://image.example.com",
        pages: 208,
        authorId: 4,
        genreId: 1,
    },
    {
        title: "The Master and Margarita",
        stock: 9,
        isbn: "9780140455465",
        imageUrl: "https://image.example.com",
        pages: 448,
        authorId: 5,
        genreId: 1,
    },
    {
        title: "A Sorcerer to the Crown",
        stock: 13,
        isbn: "9780425283370",
        imageUrl: "https://image.example.com",
        pages: 384,
        authorId: 6,
        genreId: 1,
    },
    {
        title: "Farenheit 451",
        stock: 12,
        isbn: "9780743247221",
        imageUrl: "https://image.example.com",
        pages: 256,
        authorId: 7,
        genreId: 2,
    },
    {
        title: "Brave New World",
        stock: 4,
        isbn: "9780582060166",
        imageUrl: "https://image.example.com",
        pages: 311,
        authorId: 8,
        genreId: 2,
    },
    {
        title: "Red Dragon",
        stock: 8,
        isbn: "9780708981696",
        imageUrl: "https://image.example.com",
        pages: 432,
        authorId: 9,
        genreId: 3,
    },
    {
        title: "The Exorcist",
        stock: 8,
        isbn: "9780060103651",
        imageUrl: "https://image.example.com",
        pages: 400,
        authorId: 10,
        genreId: 3,
    },
    {
        title: "In The Woods",
        stock: 11,
        isbn: "9780670038602",
        imageUrl: "https://image.example.com",
        pages: 608,
        authorId: 11,
        genreId: 3,
    },
    {
        title: "And Then There Were None",
        stock: 15,
        isbn: "9780008123208",
        imageUrl: "https://image.example.com",
        pages: 256,
        authorId: 12,
        genreId: 4,
    },
    {
        title: "The Alienist",
        stock: 7,
        isbn: "9780525510277",
        imageUrl: "https://image.example.com",
        pages: 496,
        authorId: 13,
        genreId: 4,
    },
    {
        title: "Shutter Island",
        stock: 13,
        isbn: "9780060545505",
        imageUrl: "https://image.example.com",
        pages: 380,
        authorId: 14,
        genreId: 4,
    },
    {
        title: "Jurassic Park",
        stock: 13,
        isbn: "9780099282914",
        imageUrl: "https://image.example.com",
        pages: 448,
        authorId: 15,
        genreId: 5,
    },
    {
        title: "The Lost World",
        stock: 13,
        isbn: "9780307291844",
        imageUrl: "https://image.example.com",
        pages: 393,
        authorId: 15,
        genreId: 5,
    },
    {
        title: "Red Rabbit",
        stock: 12,
        isbn: "9783453436824",
        imageUrl: "https://image.example.com",
        pages: 640,
        authorId: 16,
        genreId: 5,
    },
    {
        title: "It Ends With Us",
        stock: 13,
        isbn: "9781501110368",
        imageUrl: "https://image.example.com",
        pages: 384,
        authorId: 17,
        genreId: 6,
    },
    {
        title: "Outlander",
        stock: 21,
        isbn: "9780440212560",
        imageUrl: "https://image.example.com",
        pages: 640,
        authorId: 18,
        genreId: 6,
    },
    {
        title: "Grant",
        stock: 21,
        isbn: "9780143110637",
        imageUrl: "https://image.example.com",
        pages: 1104,
        authorId: 19,
        genreId: 7,
    },
    {
        title: "Salt: A World History",
        stock: 21,
        isbn: "9780142001615",
        imageUrl: "https://image.example.com",
        pages: 484,
        authorId: 20,
        genreId: 8,
    },
    {
        title: "The Omnivore\'s Dilemma: A Natural History of Four Meals",
        stock: 21,
        isbn: "9781594200823",
        imageUrl: "https://image.example.com",
        pages: 450,
        authorId: 21,
        genreId: 8,
    },
    {
        title: "Julie and Julia: 365 Days, 524 Recipes, 1 Tiny Apartment Kitchen",
        stock: 12,
        isbn: "9780316109697",
        imageUrl: "https://image.example.com",
        pages: 310,
        authorId: 22,
        genreId: 8,
    },
    {
        title: "Kitchen Confidential: Adventures in the Culinary Underbelly",
        stock: 21,
        isbn: "9780060899226",
        imageUrl: "https://image.example.com",
        pages: 321,
        authorId: 23,
        genreId: 8,
    },
]